language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run docs:build
after_success:
  - cd docs/.vuepress/dist
  - echo "spring-boot.cn,www.spring-boot.cn" > CNAME
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "generate static resources, triggerd by travis ci"
  - git push --force "https://${USERNAME}:${REPO_TOKEN}@${GH_REF}" master:master
